import type { Metadata } from "next";
import { fetchPage } from "../../../contentful/getPageData";
import { componentMap } from "../../componentMap";
import { useLocale } from "next-intl";

export const metadata: Metadata = {
  // TODO Update metadata according to the page
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Page() {
  const locale = useLocale();

  console.log("Locale from page with slug: ", locale);

  const page = await fetchPage("april-on-status-system");

  const RenderComponent = ({ component }: any) => {
    const Component = componentMap[component._type];

    if (!Component) {
      return null;
    }

    return <Component {...component} />;
  };

  return (
    <div>
      {page &&
        page.content.map((component, index) => (
          <RenderComponent key={index} component={component} />
        ))}
    </div>
  );
}
