version: "3.8"

services:
  web:
    build:
      context: .
      target: production # Change this to `development` for development build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
