version: "3.8"

services:
  web:
    build:
      context: .
      target: development # Change this to `production` for production build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_DELIVERY_ACCESS_TOKEN=${CONTENTFUL_DELIVERY_ACCESS_TOKEN}
    volumes:
      - .:/app
