import type { Metadata } from "next";
import "../globals.css";
import { LocalizationProvider } from "../LocalizationContext";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={params.lang}>
      <body className="prose">
        <LocalizationProvider>
          <Navbar />
          {children}
          <Footer />
        </LocalizationProvider>
      </body>
    </html>
  );
}
