import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { fetchNavbar } from "@/contentful/getLayoutData";

import { locales } from "@/app/i18n/settings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }));
}

type LayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

export default async function Layout({ children, params }: LayoutProps) {
  const locale = params.locale;
  const menu = await fetchNavbar();

  console.log("Locale: ", locale);
  return (
    <main className="prose">
      <Navbar {...menu} />
      {children}
      <Footer />
    </main>
  );
}
